version: '3'
services:
  acosshop:
    build: .
    ports:
      - 80:80
    volumes:
      - ./acg-faka:/var/www/html
    entrypoint: /bin/bash -c "service mariadb start &&chmod 777 /var/www/html&& exec apache2-foreground"
